### ISSUE TITLE
[Entry] Vue:

### ISSUE THREAD

**Issue by Armania** [Codecademy/docs#1285]
### Reason/inspiration (optional)

I noticed there is not a "Topic" dedicated to Vue or VueJS. 
Also,
- Vue: [Nuxt](https://nuxtjs.org/)
- Vue: [Pinia](https://pinia.vuejs.org/)
- Vue: [Vueuse](https://vueuse.org/)

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Armania** [comment]
I have begun writing this section and would love to make this contribution

**Comment by Armania** [comment]
Hi CC

can I work on this?

**Comment by Dusch4593** [comment]
Hey @Armania! Thank you for your interest in creating this new topic for Codecademy Docs! 🚀

Currently, we are looking to add more concepts/terms rather than new topics. Since Vue.js falls under the JavaScript of our course catalog, would you be open to creating Vue entries as concepts/terms under the existing [JavaScript topic](https://www.codecademy.com/resources/docs/javascript) in Docs?

**Comment by Dusch4593** [comment]
@Armania Happy New Year! 🎊

Please go ahead and open the PR and we'll be happy to take a look at it. 😄

**Comment by Armania** [comment]
@SSwiniarski @Dusch4593 

Created a new pull request
[Armania:new_js_concept_vuejs](https://github.com/Codecademy/docs/pull/1525)

**Comment by yangc95** [comment]
> Created a new pull request
> 
> [Armania:new_js_concept_vuejs](https://github.com/Codecademy/docs/pull/1525)

TY for the previous PR, although we had to close it since it did not meet the minimum standards in that there were too many file changes (22) and with only metadata.

Please resubmit a PR that's directly associated with this issue! If you have any specific questions don't hesitate to reach out as we're here to support ☺️ any concerns you may have are valid as well so feel free to voice any issues you have by tagging a maintainer 🙂

**Comment by SSwiniarski** [comment]
I'm going to unassign this issue as it seems to have been abandoned.

**Comment by Armania** [comment]
Hi @SSwiniarski 

Sorry for the late reply, life  and layoffs have been a distraction, but I have more time now to complete this

**Comment by SSwiniarski** [comment]
Ok, @Armania, if you're upf for working on this, I'm re-opening it for you.

**Comment by SSwiniarski** [comment]
@Armania It's been another two weeks. Are you still working on this?

**Comment by SSwiniarski** [comment]
I'm closing this as abandoned.
