### ISSUE TITLE
[Term Entry] Python Dunder Methods: `__str__()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1363]
### Reason/inspiration (optional)

Can we add a new term entry about the `__str__()` method (under the [Dunder Methods](https://www.codecademy.com/resources/docs/python/dunder-methods) concept)?

It should at least include the following sections:

- A "Syntax" section with a \```pseudo code block
- An "Example" section with a \```py code block
- A "Codebyte Example" section with a \```codebyte/python code block

Some info to look into and include:

- How the `__str__()` method compares with the `__repr__()` method.
- How the `__str__()` method works with the built-in `str()` function.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by patrickevans29** [comment]
Hi, 

I'm currently doing the Codacademy "Learn Git and Github course", I'd love to have a go at resolving this issue if possible. 

Thanks
PJ

**Comment by cacaprog** [comment]
Hi,

I'd like to try this one!
Good to review python lessons and get in github project :)

tks

**Comment by yangc95** [comment]
@patrickevans29 This issue will be assigned to you given our first-come-first-serve basis.

Thank you for your interest in this issue @cacaprog and for being patient with our processes! Although this issue will be assigned to the former contributor, there are other open issues available. Please let us know otherwise.

Happy New Year and great to have you on the Docs repo ☺️

**Comment by patrickevans29** [comment]
Great. Thanks @yangc95
