### ISSUE TITLE
[Term Entry] Pandas DataFrame: `.drop_duplicates()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1379]
### Reason/inspiration (optional)

Let's write a new entry about the `.drop_duplicates()` DataFrame method (in pandas).

Folder/file structure: `content/pandas/dataframe/drop-duplicates/drop-duplicates.md`

Make sure to include the following sections:

- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with a \```py code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Intern5000** [comment]
Hello, I am taking the Git/Github learning course, and I would like to know if I could be assigned to this. Thank you!

**Comment by Dusch4593** [comment]
Sure thing, @Intern5000! You're assigned and thank you for contributing to Codecademy Docs! 😄

**Comment by fabiomignardi** [comment]
Hello there! I would like to contribute on this issue, I'm training on Git-Github course and I was wondering If I could be assigned to this one. Many thanks in advance!

**Comment by KTom101** [comment]
@fabiomignardi This is currently assigned to @Intern5000. Please check to see if there is an unclaimed [issue](https://github.com/Codecademy/docs/issues) you would like to be assigned to.

**Comment by Intern5000** [comment]
Hey, sry for the delay.
I will probably not be able to do it in the next two weeks.
You can unassign me.
Kind regards

Von: SSwiniarski ***@***.***>
Gesendet: Montag, 16. Januar 2023 16:11
An: Codecademy/docs ***@***.***>
Cc: Mayer, Thilo ***@***.***>; Mention ***@***.***>
Betreff: Re: [Codecademy/docs] [Term Entry] Pandas DataFrame: `.drop_duplicates()` (Issue #1379)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>
EXTERNAL EMAIL

@Intern5000<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIntern5000&data=05%7C01%7Cthilo.mayer%40stryker.com%7C615c7a59e1574397ab0e08daf7d3d73f%7C4e9dbbfb394a4583881053f81f819e3b%7C0%7C0%7C638094786471412050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FddwhLlpnsX84y6IJO5EBHpRpUpeZPk0g%2FS8PL2PmoM%3D&reserved=0>, it's been two weeks, are you still working on this PR? Do you need assistance?

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCodecademy%2Fdocs%2Fissues%2F1379%23issuecomment-1384194358&data=05%7C01%7Cthilo.mayer%40stryker.com%7C615c7a59e1574397ab0e08daf7d3d73f%7C4e9dbbfb394a4583881053f81f819e3b%7C0%7C0%7C638094786471412050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F4qvWFPRi7imiyMMX0pnvy3cbnQnMs6BSDOk3iPvtuM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA252VJKG25JL66QAD5RI54TWSVQHJANCNFSM6AAAAAATIYM4UM&data=05%7C01%7Cthilo.mayer%40stryker.com%7C615c7a59e1574397ab0e08daf7d3d73f%7C4e9dbbfb394a4583881053f81f819e3b%7C0%7C0%7C638094786471412050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f5jcRr9wy09DCH9CYWzsaF5c9r%2FFb0T%2FodpknBSAZto%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: External email. Do not click links or open attachments unless you recognize the sender and know the content is safe. Please forward all suspicious emails to ***@***.***

Follow this link to read our Privacy Statement<https://www.stryker.com/content/stryker/gb/en/legal/global-policy-statement.html/>

**Comment by SSwiniarski** [comment]
Ok, I'm unassigning @Intern5000. @fabiomignardi, are you still interested in working on this issue?

**Comment by OBartoz** [comment]
Hi, I'm trying to complete my github portfolio. Can I be assigned this issue?

**Comment by Dusch4593** [comment]
Sure thing, @OBartoz! You are assigned. 😄

Just curious, how did you learn about Codecademy Docs and about contributing to it?

**Comment by OBartoz** [comment]
Thanks, @Dusch4593! 
I was trying to complete the datascience pathway on codecademy, then started the github skill in order to portfolio my work :)
