### ISSUE TITLE
[Entry] Subject: GitHub GraphQL API

### ISSUE THREAD

**Issue by ARBUCHELI** [Codecademy/docs#1972]
### Reason/inspiration (optional)

I noticed there is not a "Topic" dedicated to GraphQL API, and maybe this could be a good first topic for getting started with GraphQL for some students.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by WiggleXO** [comment]
Hi, I'm interested in working on this issue.

**Comment by yangc95** [comment]
@ARBUCHELI There is currently a GraphQL concept entry here: https://www.codecademy.com/resources/docs/open-source/graphql

I'm wondering how you were thinking of breaking down GraphQL into concepts.

@WiggleXO Thanks for your interest, please stand-by while we discuss this!

**Comment by yangc95** [comment]
@ARBUCHELI Due to the time that has elapsed, I think we'll go ahead and close this for now as new topics need to be approved internally. For a topic to be created, there needs to be some outline for the concepts and terms that will populate the topic. If you wish to continue this conversation at any time in the future, please head over to Forums where we can discuss further!

See [find-a-starting-point-possible-content-discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868/6)
