### ISSUE TITLE
[Term Entry] JavaScript Dates .setMilliseconds()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2431]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.setMilliseconds()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/setMilliseconds/setMilliseconds.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yashi11** [comment]
Hey!!
May I help in this one under Social Summer of Code 2023??
Regards

**Comment by SSwiniarski** [comment]
@Yashi11 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@Yashi11 Also note that we limit folks to claiming no more than three open issues at a time. Please submit PRs for your claimed issues before attempting to claim any new ones.

**Comment by SSwiniarski** [comment]
@Yashi11 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

**Comment by drewbie1234** [comment]
I will happily take on the Term Entry if available?

**Comment by drewbie1234** [comment]
# .setMilliseconds()

In JavaScript, dates are represented using the Date object. The Date object provides various methods to manipulate and retrieve components of a date and time.

The **.setMilliseconds()** method allows you to set the milliseconds part of a Date object to a new value. It takes an integer argument ranging from 0 to 999, representing the new milliseconds value you want to set.

Only the milliseconds part of a date and time is modified.

The .setMilliseconds() method modifies the original Date object in place, it updates the milliseconds value directly on the object without creating a new Date object. 

Remember that the .setMilliseconds() method returns the new timestamp value, which represents the number of milliseconds since January 1, 1970 00:00:00 UTC.

## Syntax

```
dateObject.setMilliseconds(n)
``` 

where n is an integer between 1 and 999 

## Example

Here's an example that demonstrates how to use the .setMilliseconds() method:

## Codebyte Example


JavaScript:
```
var date = new Date();
console.log("Original date:", date);  // Output: Original date: Sun Jun 23 2023 12:34:56 GMT+0000 (Coordinated Universal Time)

date.setMilliseconds(123);
console.log("Modified date:", date);  // Output: Modified date: Sun Jun 23 2023 12:34:56.123 GMT+0000 (Coordinated Universal Time)
```

In this example, we create a new Date object and retrieve the original milliseconds value using the .getMilliseconds() method. Then, we use the .setMilliseconds() method to change the milliseconds value to 456. Finally, we retrieve the modified milliseconds value using .getMilliseconds() again and display it.

```codebyte/js
var date = new Date();
console.log("Original date:", date);

date.setMilliseconds(123);
console.log("Modified date:", date);
```

**Comment by SSwiniarski** [comment]
@drewbie1234 Two things: One, @Yashi11 is still assigned this entry, so they have another week to submit a PR. Two, you shouldn't write an entry before being officially assigned, which is to avoid just this, two people working on the same entry.

If @Yashi11 hasn't responded at the end of a week, I'll assign you.

**Comment by Yashi11** [comment]
> @Yashi11 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

Will be updating this weekend.

**Comment by Yashi11** [comment]
> > @Yashi11 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.
> 
> Will be updating this weekend.

Sent PR for the same.
