### ISSUE TITLE
[Term Entry] PHP String Functions str_pad()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2434]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `str_pad()` function.

The entry should go in a new file in `docs/content/php/concepts/string-functions/terms/str-pad/str-pad.md` (Note the path uses dashes, not underscores.)

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by phuongtrieu97coder** [comment]
I would like to work on this issue

**Comment by SSwiniarski** [comment]
@phuongtrieu97coder You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by phuongtrieu97coder** [comment]
This is my first time contributing, I decide to contribute to some repository on Codecademy docs because a course from Codecademy named Learn Git & GitHub requires me to do it. I chose this repo because I learned PHP 1 year ago. Although I didn’t work with it for a long time, I still have documents about it, and I think I can do research about it to contribute to this repository.  Sent from Mail for Windows From: SSwiniarskiSent: Wednesday, June 21, 2023 9:31 AMTo: Codecademy/docsCc: Phuong Trieu; AssignSubject: Re: [Codecademy/docs] [Term Entry] PHP String Functions str_pad() (Issue ***@***.*** You're assigned! You can check out the Contribution Guide for additional information on contributing.See Content Standards for an overview of styling tips that the Style Guide covers in detail.After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.In addition, please head over to the Docs Forum if you have any questions about Docs or reply to the thread on Possible Content Discussion to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!If this is your first time contributing, can you let us know how you came across this repo?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by phuongtrieu97coder** [comment]
This is my first time contributing, I decide to contribute to some repository on Codecademy docs because a course from Codecademy named Learn Git & GitHub requires me to do it. I chose this repo because I learned PHP 1 year ago. Although I didn’t work with it for a long time, I still have documents about it, and I think I can do research about it to contribute to this repository.
