### ISSUE TITLE
[Concept Entry] C# Classes

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2758]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about classes.

The entry should go in a new file in `docs/content/c-sharp/concepts/classes/classes.md`

The entry should 

- Explain what classes are and the syntax for declaring them.
- Explain properties and methods.
- Explain access modifiers.
- Provide a code example of a class in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@SAbubakarQ  You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SAbubakarQ** [comment]
Hello @KTom101! I will be sure to look at that. Yes, this is my first contribution to Codecademy Docs. I am happy to contribute! I am taking the Git/Github course on Codecademy to help me better understand how it works.

**Comment by SAbubakarQ** [comment]
Hello @KTom101 , I am having this issue when pushing changes: 
![image](https://github.com/Codecademy/docs/assets/65397022/e9e9cbaa-8b10-45ae-86bd-0a3ed953476a)

**Comment by KTom101** [comment]
@SAbubakarQ Thank you for sending the screenshot 🙂 It looks like you're trying to push to the original Docs repo rather than your forked local repo. Please take a look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) again; [specifically here](https://www.codecademy.com/resources/docs/contribution-guide/creating-a-pull-request-and-revisions#:~:text=summary%20of%20changes.%22-,Push%20your%20changes%20on%20the%20separate%20branch,-You%20now%20have).

**Comment by SSwiniarski** [comment]
@SAbubakarQ It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SAbubakarQ** [comment]
Yes, currently working on solving the issue I was having earlier. Will get to it before EOD. Thanks,- Abubakar QasimOn Aug 5, 2023, at 12:32 PM, SSwiniarski ***@***.***> wrote:﻿
@SAbubakarQ It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by caupolicandiaz** [comment]
This has been reopened, because of the lack of progress made by the previous contributor.

**Comment by narcissus123** [comment]
@caupolicandiaz Can you please assign this issue to me.

**Comment by caupolicandiaz** [comment]
@narcissus123 You're all set

**Comment by narcissus123** [comment]
Thank you for assigning me to this issue.
