### ISSUE TITLE
[Term Entry] HTML Semantic HTML <rb>

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2763]
### Reason/inspiration (optional)

We would like a new term entry for HTML [Semantic HTML](https://www.codecademy.com/resources/docs/html/semantic-html) about the <rp> tag. The entry should go in a new file in docs/content/html/concepts/semantic-html/terms/rp.md

The entry should
    - Have an introductory paragraph about what the tag is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the tag in use.
    - An image if desired

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by CBID2** [comment]
I know just the right person for this.  @elliezub, check this out.

**Comment by elliezub** [comment]
Thanks Chrissy! I would like to be assigned to this if possible :)

**Comment by KTom101** [comment]
@elliezub You're assigned 🎉

**Comment by elliezub** [comment]
Hi, I see the title says to make an entry on <rb>, but <rb> along with <rt> or <rp> must be within the <ruby> tag. Since there is not an entry on <ruby>, I think it makes more sense to do the entry on <ruby> and mention those tags in the entry. 

Another thing to note is that <rb> is deprecated, so I am not sure whether to include <rb> or instead just make the entry on <ruby> and include <rp> and <rt>.

Please let me know how I should proceed :) Thanks!

**Comment by elliezub** [comment]
Hi, I see the title says to make an entry on `<rb>` but `<rb>` along with `<rt>` or `<rp>` must be within the `<ruby>` tag. Since there is not an entry on `<ruby>`, I think it makes more sense to do the entry on `<ruby>` and mention those tags in the entry. 

Another thing to note is that `<rb>` is deprecated, so I am not sure whether to include `<rb>` or instead just make the entry on `<ruby>` and include `<rp>` and `<rt>`

Please let me know how I should proceed :) Thanks!

**Comment by CBID2** [comment]
> Hi, I see the title says to make an entry on `<rb>` but `<rb>` along with `<rt>` or `<rp>` must be within the `<ruby>` tag. Since there is not an entry on `<ruby>`, I think it makes more sense to do the entry on `<ruby>` and mention those tags in the entry.
> 
> Another thing to note is that `<rb>` is deprecated, so I am not sure whether to include `<rb>` or instead just make the entry on `<ruby>` and include `<rp>` and `<rt>`
> 
> Please let me know how I should proceed :) Thanks!
Hi @elliezub! :) Turns out someone else did an entry on Ruby. It's PR

**Comment by elliezub** [comment]
So is there still an entry needed for `<rb> `? it looks like the new entry on ruby includes `<rp>` and `<rt>` 

`<rb>` is deprecated as you can see below 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb

**Comment by KTom101** [comment]
@elliezub This can still be added. Please add a block quote note (`> **Note:**`) after the introduction paragraph noting that the tag is deprecated.

**Comment by elliezub** [comment]
Ok, will do! Thank you

**Comment by SSwiniarski** [comment]
@elliezub It's been two weeks. Are you still working on this issue? We'd expect a PR within the next week or this will be unassigned due to inactivity.

**Comment by elliezub** [comment]
Hi, sorry about that! I wanted to work on it earlier but wasn't sure how to proceed. I just got back from a trip, so I will send the PR today :)
