### ISSUE TITLE
[Entry Request] What is Server-side Rendering?

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#279]
## Description

Write a "What is Server-side Rendering?" article in the General section if you have an advanced web dev background.

General: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by demonicirfan** [comment]
Can i work on this

**Comment by sonnynomnom** [comment]
Absolutely!

**Comment by sonnynomnom** [comment]
@demonicirfan how did you find this by the way?

**Comment by demonicirfan** [comment]
github explore section 😊

**Comment by sonnynomnom** [comment]
Oh wow. So through #hacktoberfest or no? (Just wondering!)

**Comment by demonicirfan** [comment]
yes through hacktoberfest

**Comment by sonnynomnom** [comment]
Awesome!

**Comment by sonnynomnom** [comment]
Awesome! Looking forward to your PR. Each PR will be reviewed by two maintainers. So take your time and make sure it's about quality not just quantity!

**Comment by demonicirfan** [comment]
# What is Server-side Rendering

Server-side rendering is rendering the content in the server and presenting it to the client when a request is made. While in the client-side rendering when a request is made the content is rendered in the browser. Javascript works both on server and browser, so it is possible for us to render the content of a application where we want. 

## Why Server-side Rendering is Important

- When the content is rendered on the server, the time required for downloading, parsing, and executing the javascript code is reduced. Thus the load time is reduced and performance is improved.

- Server-side rendering helps improve SEO by pre-rendering the page so that when a search engine crawls the website it is able to get some content as compared to a client-side rendered page, which is served as an empty HTML file with links to javascript. And fast load time also helps the site to rank higher in search results.

@sonnynomnom  i never wrote a blog before, what can be improved in this
