### ISSUE TITLE
[Term Entry] PHP Arrays array_chunk()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2875]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `array_chunk()` function.

The entry should go in a new file in `docs/content/php/concepts/arrays/terms/array-chunk/array-chunk.md` (Note the dashes rather than underscores) 

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MellowZippy1** [comment]
I would like to work on this issue.

**Comment by KTom101** [comment]
@MellowZippy1 Please refrain from opening a PR before being assigned.  In the future, wait for a maintainer to assign you first. This makes for a better workflow and prevents others from claiming an issue that you were already working on. 


I'm also seeing that you have two GitHub usernames associated with your commit causing a CLA conflict.  You will need to check your [GitHub configuration](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git?platform=linux) so that it's configured to the correct account. You may also have to close out your PR and resubmit.
