### ISSUE TITLE
Documentation Entry Edit: HTML, CSS, and Markdown Improvements

### ISSUE THREAD

**Issue by Tham-er** [Codecademy/docs#3185]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting, Add new content (definitions, codeblocks, etc.)

### Description (optional)

Hi Codecademy,

I'm excited to start contributing to the Codecademy documentation repository project, and I'm looking for a task to work on as part of my project. I have experience with HTML, CSS, and Markdown, and I'm eager to make meaningful contributions to improve the documentation.

Could you please suggest a specific task or point me in the right direction? Whether it's fixing typos, formatting improvements, or any other documentation-related task, I'm ready to get started. Your guidance will be greatly appreciated.

Thank you for the opportunity to contribute, and I look forward to collaborating with the community!

Best regards,

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by shikha-echtops** [comment]
@jakemhiller  I am intrested in taking this issue on .

**Comment by Aysledger** [comment]
Hi, I would like to take this issue.

**Comment by SSwiniarski** [comment]
@Tham-er we appreciate your eagerness, but we want issues to encompass a specific task. If you want to address typos or clarity in some entries, then go ahead, but if you want to  create an issue for them, you'll need to specify what entries.

Also, if you just want to fix a typo, you can go ahead and submit a PR for it, you don't need to create an issue first.

As it is, I'm going to close this issue because it doesn't address anything specific.
