### ISSUE TITLE
[Edit] HTML Add Media: src

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3335]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the HTML Attributes entry. The entry lives in docs/content/html/concepts/attributes/terms/src.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by OdiriTeddie** [comment]
@yangc95 I am interested in taking this issue on. Found out about docs from the Codecademy platform.

**Comment by kevuschka** [comment]
I'm interested in this issue, too!

**Comment by IAmRiteshKoushik** [comment]
Hey, I would like to take up this issue. Can I have it assigned to me ?

**Comment by Shiv10122003** [comment]
hey , i would like to take that issue

**Comment by KTom101** [comment]
@OdiriTeddie Since you asked first, I'm assigning you. Please keep in mind that this issue is asking for you to add images showing what the examples would look like when executed. In addition to the documents linked in the description, please take a look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't done so already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Docs? If so, how did you find out about contributing to Docs?

**Comment by KTom101** [comment]
@IAmRiteshKoushik @Shiv10122003 Since the other contributor asked first, this has been assigned to them. Please look for a different [unassigned issue](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) to work on. Also, check back regularly, we are always adding more issues.

**Comment by SSwiniarski** [comment]
@OdiriTeddie It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by OdiriTeddie** [comment]
Yes I am, sorry I got a little tied up with work but I'm done and have started working on it.

**Comment by SSwiniarski** [comment]
@OdiriTeddie I unassigned you because your PR did not actually address the issue, which was to insert an illustrative image into the src entry.

**Comment by cslylla** [comment]
I can add an image and a gif to showcase the usage of `<img>` and `<video>` tags.

**Comment by A-Kiwams** [comment]
I would like to take up this issue

**Comment by SSwiniarski** [comment]
@cslylla, You're assigned.

@A-Kiwams, @cslylla claimed this first.
