### ISSUE TITLE
[Term Entry]: Linked_List.md 

### ISSUE THREAD

**Issue by Bratajit-03** [Codecademy/docs#3682]
### Reason/inspiration (optional)

i want to add the concept of linked list to c present under contents.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by Carloscode5** [comment]
@yangc95 I am interested in taking this issue on, I found out about Docs through Codecademy's Git/GitHub Course.

**Comment by JatinPhogat** [comment]
Hey ,can i work on this i am deep understanding of dsa . i can do it well . Please assign it to me @yangc95

**Comment by KTom101** [comment]
@Bratajit-03 I see you closed this out. But so you know, this would not be in scope with Docs since it is not a built-in feature. This is more fit for a UGC article. An issue for this can be opened in the [UGC repo](https://github.com/Codecademy/ugc/issues), if you choose. You would also have to wait for assignment once posted.
