### ISSUE TITLE
[Edit] Arrays: Adding codebyte for `arrays.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4136]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the arrays entry. The term entry lives in docs/content/javascript/concepts/arrays/arrays.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add code byte showing all how to create the array and then print it out in the console. Make sure the way to create an array is as per the entry. If you add a new way that is not present in the entry then add it in the entry too.
2) Add code byte showing how to access the Elements of an Array.
3) You can be creative with the codebyte example too. But make sure not to differ a lot from the current entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
@deenovita You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by SSwiniarski** [comment]
@deenovita It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by tsirianni** [comment]
@SSwiniarski, if this issue becomes available I would like to contribute to it. Thank you!

**Comment by deenovita** [comment]
> @deenovita It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

Hello, I apologize for the inactivity and the inconvenience. I have unassigned myself from the issue and let others work on it. Thank you

**Comment by AlessioAltomonte** [comment]
@dakshdeepHERE Hi there, may I work on this issue please? thanks

**Comment by SSwiniarski** [comment]
@tsirianni You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@AlessioAltomonte, @tsirianni asked to be assigned first.

**Comment by AlessioAltomonte** [comment]
@SSwiniarski I see, I shall find a different issue to contribute on then. thanks

**Comment by tsirianni** [comment]
Just to be sure, would you @dakshdeepHERE or @SSwiniarski be so kind as to confirm whether you would like new content/examples to be added to the entry or should I just transform the current code blocks (creating and accessing element) into codebyte blocks?

Also, I do have a few suggestions but I would like to confirm whether or not they make sense/are acceptable prior to opening the PR, since they may be out of the issue's scope:

1 - There are examples with an array called `fruit` but since the variable is essentially storing a list, I would like to place the variable in its plural form, as `fruits`.

2 - In the **Creating an Array** section, it shows the most straightforward way to create an array followed by a code block, but I believe the intended word to demonstrate the code's location was **below** instead of **above**.

3 - I noticed that all the examples creating an array have values that are primitive values. I would like to suggest including an example to showcase that an array can also receive variables as values, not just the primitives, something like:

```js
const rockSong = 'Master of Puppets';
const popSong = 'Bad Romance';

const songs = [rockSong, popSong];
console.log(songs); // Outputs: ['Master of Puppets', 'Bad Romance']
```

PS: Is there a way to test the codebyte block locally? I have not found in any of the guides how to do so nor have I found a script in package.json that would help me with that.

Thank you, looking forward for the reply and opening the PR! :)
