### ISSUE TITLE
[Bug/Error] Need Better Term Table Naming

### ISSUE THREAD

**Issue by hughlilly** [Codecademy/docs#466]
### Actual Behavior

On [the page about lists in Python](https://www.codecademy.com/resources/docs/python/strings), the `h2` heading after the content just says "Lists":

<img width="620" alt="image" src="https://user-images.githubusercontent.com/12046008/146092348-c62017d3-0ff5-402e-a59f-e7c2bdf5e069.png">

The same is true of [the page for Strings](https://www.codecademy.com/resources/docs/python/strings), and, I presume, all other pages which list methods like this.

### Expected Behavior

The heading should be "`<entry name>` methods", in my opinion. I can't find where in the repo this is controlled but I would be happy to update these if someone wanted to point it out.

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Dusch4593** [comment]
Great catch, @hughlilly! Thank you for bringing attention to this 😄 Since this issue relates to the actual Docs site, I wanna defer to one of the engineers for this one (cc: @christian-dinh) to see how to move forward.

**Comment by hughlilly** [comment]
Thanks. For what it's worth I also think the middle section of the content could be wider. As a test I set the navigation sidebar to 2 wide and the middle portion to 7:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/12046008/146106497-49cbd719-b2a2-46fa-9f87-5994486ceae5.png">

This would allow for much easier reading, particularly with regard to long single lines of code in code blocks.

Thanks
Hugh

**Comment by Dusch4593** [comment]
Hi @hughlilly! Wanted to follow up with you 😃 

Regarding the naming issue, this seems to be a temporary workaround for the different kinds of "terms" that could be tabulated (methods, tags, functions, etc.). 

Folks in Engineering and Product have been informed of the points you brought up in this issue. For now, until I hear otherwise, we're going to hold off on this issue by keeping it up with a "wont fix" label. In the meantime, Engineering can look into the "naming of terms tables" issue while Product explores the other concern (about content width) a little further.

Thank you again, Hugh, for creating this issue (and all your other work on Codecademy Docs thus far!). For the New Year, the teams that help maintain Docs want its growth to be as community-driven as possible, even with the site! 🎉

**Comment by hughlilly** [comment]
@Dusch4593, thank you so much for the quick response. 😎
