### ISSUE TITLE
[Term Entry] PyTorch Tensors .unsqueeze()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5065]
### Reason/inspiration (optional)

Add a new term entry about the `.unsqueeze()` method for Tensors. Place your file under the file path `docs/content/pytorch/concepts/tensors/terms/unsqueeze/unsqueeze.md` 

It should include the following sections:

- A "Syntax" section with a \```pseudo code block
- An "Example" section with a \```py code block

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by codeerfreak** [comment]
Hello, my name is Eric, currently i am learning the "Full Stack software engineer" here @ Codecademy. In this course the information on git and github was a bit underwhelming, so i thought to do the Git and Github course...I love this course, but now i am stuck; i am asked to pick one of the unassigned issues in Codecademy docs, and work on it. My knowledge of these issues is non-existent. I am very new in programming, that's why i took the Full stack engineer course.

My question is, what to do now, so i can proceed with the course...
Any advise is more than welcome!
Hope my English is good enough....

Have a nice day,  Eric

**Comment by SaviDahegaonkar** [comment]
Hi Eric,
First of all, welcome to the programming world! It's great that you're taking the initiative to learn more about Git and GitHub—it’s a crucial skill to learn.

When picking an issue to work on, don't worry about having little experience. Everyone starts somewhere; the key is approaching this as a learning opportunity. Try to read the issue a few or more times. Understand the concept about which the issue is written, You can use various resources for this, and I am quite confident you will find your way through this. All the Best.

For now, I would like to know if would you like to work on this issue.

Thanks & Regards,
Savi

**Comment by codeerfreak** [comment]
Hi Savi,
Many thanks for your reply. You gave me enough confidence to take this issue, and solve it. 
So yes i want to work on this issue.

Kind regards,
Eric

**Comment by mamtawardhani** [comment]
Hey @codeerfreak You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
