### ISSUE TITLE
[Concept Entry] Sklearn self-training

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5075]
### Reason/inspiration (optional)

We would like a new entry on the `Self Training` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/self-training/self-training.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use (if applicable)
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use (if applicable)

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by dani-svdra** [comment]
hi, I am interested in working on this activity as a new learner @codecademy-docs

**Comment by mamtawardhani** [comment]
Hey @dani-svdra You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by dani-svdra** [comment]
good morning @mamtawardhani hope u doing well, I am very new on this and I am a bit confused yet in what a can contribute to, I was following the path for "learn git and git hub" in the section number 9 "contributing to the code academy docs repository". I am understanding the concepts but not sure yet about contributions since my knoledge it is very limited; however I think I could contribute with a research in html, I was checking on "lists and tuples in Python" something I like to inquire a bit, but then I think that I should not be doing so through this sklearn which seems very advance for me. So I believe I will try to reject this one and try writting dow on that one. I want to apologize with you, I am still getting use to everything we must manage in github. Ty much relly appreciate it.

**Comment by dani-svdra** [comment]
@mamtawardhani afternoon, not sure but I think I posted incorrectly, u sent me the feedback in the other message so not sure ty
