### ISSUE TITLE
[Term Entry] Python built-in functions iter()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5115]
### Reason/inspiration (optional)

We would like a new term entry on the `iter()` built-in function in Python. The entry should go in a new file under `docs/content/python/concepts/built-in-functions/terms/iter/iter.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Varun2711** [comment]
Hey! I'd like to work on this!

**Comment by SaviDahegaonkar** [comment]
Hello @Varun2711 ,

You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by Varun2711** [comment]
Hello @SaviDahegaonkar ,

Sorry for the late reply. I have been using Codecademy since the end of 2022. I was creating a rough timeline to finish up the fullstack engineering certificate as I have a bit more time on my hand this year and recently I was going over the projects that I had started or completed and stumbled upon the docs contribution project in there.  This is my first time contributing to an open source project, so I apologize for any delays that occur. I'm currently cross checking my work with the official python docs to make sure I have not written anything misleading.

Sincerely,
Varun
