### ISSUE TITLE
[Entry] General: File Paths

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#619]
### Reason/inspiration (optional)

Include what file paths are and how they are determined. Such as when and how many `/` and `.` to use.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ethan-master-coding** [comment]
@Dusch4593 I noticed we have a file path entry for HTML. Should we make a general entry by copying and pasting the HTML one and removing all references to HTML?

**Comment by Dusch4593** [comment]
@ethan-master-coding yeah that seems fine

**Comment by ethan-master-coding** [comment]
@Dusch4593 Got it. Can you assign this to me?

**Comment by ethan-master-coding** [comment]
@Dusch4593 So I accidentally added more commits to my `ethan-master-coding:main`. So if I fork it to an org I own will the contribution still count towards me as long as I open the PR?

**Comment by Dusch4593** [comment]
@ethan-master-coding Sorry for the delay on this one. I wanted to check with my team before sharing potential fixes with you. I would recommend looking at and possibly following the steps in [this GitHub gist](https://gist.github.com/seLain/8bdf12c7196f3fccafdf067dec2696b2) about what do in a situation like this. **However**, I recommend following these steps _**first**_:

1. Since `git rebase` is kind of destructive you might want to backup your fork locally before trying out the steps in the link above.
2. When following the steps in the gist, use `main` instead of `master`.

Let me know if you end up giving this a try and what happens. 😄

**Comment by ethan-master-coding** [comment]
@Dusch4593 whatever I did, did not work. What I plan to do is once #757 and #760 are merged I delete my fork and then fork this repo again so it's all good. But if I use a fork owned by a GH ORG what will happen to that contribution on the leaderbord?

**Comment by Dusch4593** [comment]
@ethan-master-coding Your contribution count on the Docs leaderboard should not be affected.
