### ISSUE TITLE
[Edit] Contribution guide: PR checks

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#641]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

Add what each check for a PR does in the contribution guide. Ex. the `license/cla` check is for signing the license.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by ethan-master-coding** [comment]
@Dusch4593 Labels arent added. We need:
`documentation` added and `typo` removed.

**Comment by Dusch4593** [comment]
@ethan-master-coding Could you tell us a little more about the edits proposed in this issue? (which file(s), etc.)

**Comment by ethan-master-coding** [comment]
@Dusch4593 Edited the OP for more clarity.

**Comment by Dusch4593** [comment]
Ok gotcha. I don't think this sort of change would be useful for contributors since my Team and I are currently working on internal tooling to streamline the PR checks as much as possible. We want all contributors to have a smooth experience with Docs, where they can comfortably write/edit an entry and not get led astray by the PR checks.

Our engineering uses [GitHub actions](https://docs.github.com/en/actions) whenever pushes are made to the base `main` branch or there is activity on an open PR. We [switched over](https://github.com/Codecademy/docs/pull/392) from [CircleCI](https://circleci.com/integrations/github/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-nbLd-maxConv-lg-nb&utm_term=g_p-continuous%20integration%20github_c__rsa2_20210527&utm_content=sem-google-dg--uscan-en-nbLd-maxConv-lg-nb_keyword-text_rsa-githubCI_mixed-&gclid=Cj0KCQjw8_qRBhCXARIsAE2AtRYrrjlWKsMJVr8FtDIUawlF8mglLM-DRdAlq-sbBg0i7fHVWZL9alEaAuyJEALw_wcB) because it is less code and we find it to be more maintainable.

**Comment by Dusch4593** [comment]
@ethan-master-coding Would you like to be assigned to issue #579 instead?

**Comment by ethan-master-coding** [comment]
@Dusch4593 Sure
