### ISSUE TITLE
[Entry] Java: Stacks

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#706]
### Reason/inspiration (optional)

Can we write a concept entry about Java stacks that includes "Syntax" and "Example" sections?

Also, make sure to include language that clearly differentiates a _stack_ from a _queue_.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sanvisharma003** [comment]
heyy.. i can work on this issue.. 
i have to explain everything about stacks iguess? can i use java to do this?

**Comment by Dusch4593** [comment]
@sanvisharma003 You're assigned! Thank you for your interest in contributing to Docs. 😄 

Yes, you can use Java to discuss or provide examples of stacks (using a \```java code block). I would also recommend checking out the [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), [catalog content](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md), and [entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) for guidance on writing this entry. Let us know if you have any thoughts or questions. Happy Hacktoberfest! 🍂 💻

**Comment by SSwiniarski** [comment]
@sanvisharma003, I unassigned you because the entry you provided didn't follow our content standards, and went some weeks without any edits. Feel free to reclaim this or another issue in the future when you have time, but please review the [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), [catalog content](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md), and [entry template] (https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) entries in the documentation.

**Comment by elmanorc** [comment]
Hi! I'd like to work on this issue.

**Comment by SSwiniarski** [comment]
@elmanorc, youre assigned. Thanks for contributing. Can I ask how you came across this repo?

**Comment by elmanorc** [comment]
> @elmanorc, youre assigned. Thanks for contributing. Can I ask how you came across this repo?

Thanks. I came here through Codecademy's Git and GitHub course.
