### ISSUE TITLE
[Edit] C++ Math Functions: `cos()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#976]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [cos()](https://www.codecademy.com/resources/docs/cpp/math-functions/cos) term entry under the C++: Math Functions concept.

Under `cpp/concepts/math-functions/terms/cos/cos.md`, please make the following edits:

- Revise the opening sentence to refer to the term "cos()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `cos()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `cos()` function to..." should be revised to something akin to "The following example uses the `cos()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by adityaonstage** [comment]
@Dusch4593  Please assign this issue  to me.

**Comment by Dusch4593** [comment]
You got it, @adityaonstage! You are assigned 😎

Just a heads up, though. Since you're currently working on multiple issues (the other one being #918) make sure to create _separate pull requests that each address a single issue_. So for example, in your situation, you'd create one PR to fix this issue regarding the C++ math function `cos()` and then you'd make another one to fix #918 regarding the Java math method `.tanh()`.

**Comment by SSwiniarski** [comment]
Closing this because the cos entry has been created, though I can't find the PR for it.
